refactor: improve messages

diff --git a/zvault b/zvault
--- a/zvault
+++ b/zvault
@@ -33,7 +33,7 @@
 
 if [[ "${1}" != 'store' ]] && [[ "${1}" != 'install' ]] \
     && [[ "${1}" != 'encrypt' ]] && [[ "${1}" != 'decrypt' ]]; then
-  echo 'Unrecognized sub-command' >&2
+  echo 'Unrecognized sub-command' 1>&2
   exit 1
 fi
 
@@ -53,8 +53,14 @@ fi
 function encrypt {
   local name_of_encrypted_file="$(basename ${1}).enc"
   echo "${PASSPHRASE}" | gpg --batch --yes --passphrase-fd 0 \
-    --output "${name_of_encrypted_file}" --symmetric --cipher-algo AES256 "${1}"
-  mv -v "${name_of_encrypted_file}" "${2}/"
+    --output "${name_of_encrypted_file}" --symmetric --cipher-algo AES256 "${1}" >/dev/null
+  local gpg_exit_status=${pipestatus[2]}
+  if [[ ${gpg_exit_status} -ne 0 ]]; then
+    return ${gpg_exit_status}
+  fi
+  if mv "${name_of_encrypted_file}" "${2}/" >/dev/null; then
+    echo "ENCRYPTED: ${1} -> ${2}/${name_of_encrypted_file}"
+  fi
 }
 
 ## @param $1 Path of encrypted file.
@@ -62,11 +68,17 @@ function encrypt {
 function decrypt {
   local name_of_plaintext_file="$(basename -s .enc ${1})"
   echo "${PASSPHRASE}" | gpg --batch --yes --passphrase-fd 0 \
-    --output "${name_of_plaintext_file}" --decrypt "${1}"
-  mv -v "${name_of_plaintext_file}" "${2}/"
+    --output "${name_of_plaintext_file}" --decrypt "${1}" >/dev/null
+  local gpg_exit_status=${pipestatus[2]}
+  if [[ ${gpg_exit_status} -ne 0 ]]; then
+    return ${gpg_exit_status}
+  fi
+  if mv "${name_of_plaintext_file}" "${2}/" >/dev/null; then
+    echo "DECRYPTED: ${1} -> ${2}/${name_of_plaintext_file}"
+  fi
 }
 
-## @param $1 Config line.
+## @param $1 Line from config file.
 function infer_globals_from_config_line {
   permissions="${${(s: :)1}[3]}"
   full_dir_of_installation="${${${(s: :)1}[2]}/'~'/${HOME}}"
@@ -77,32 +89,34 @@ function infer_globals_from_config_line {
 }
 
 if [[ "${1}" = 'store' ]]; then
+  typeset -i exit_code=0
   while IFS='\n' read -r line; do
     infer_globals_from_config_line "${line}"
     if ! [[ -f "${full_path_of_plaintext_file}" ]]; then
-      echo "Skipping '${full_path_of_plaintext_file}', it does not exist"
+      echo "Error: No such file: '${full_path_of_plaintext_file}'" 1>&2
+      exit_code=1
     else
       encrypt "${full_path_of_plaintext_file}" "${full_dir_of_encrypted_file}"
       chmod "${permissions}" "${full_path_of_encrypted_file}"
     fi
   done <<< "$(cat "${2}")"
-  exit 0
+  exit ${exit_code}
 fi
 
 if [[ "${1}" = 'install' ]]; then
+  typeset -i exit_code=0
   while IFS='\n' read -r line; do
     infer_globals_from_config_line "${line}"
     if ! [[ -f "${full_path_of_encrypted_file}" ]]; then
-      echo "Skipping '${full_path_of_encrypted_file}', it does not exist"
-    elif [[ -f "${full_path_of_plaintext_file}" ]]; then
-      echo "Skipping '${full_path_of_encrypted_file}', exists: '${full_path_of_plaintext_file}'"
+      echo "Error: No such file: '${full_path_of_encrypted_file}'" 1>&2
+      exit_code=1
     else
       mkdir -p "${full_dir_of_installation}"
       decrypt "${full_path_of_encrypted_file}" "${full_dir_of_installation}"
       chmod "${permissions}" "${full_path_of_plaintext_file}"
     fi
   done <<< "$(cat "${2}")"
-  exit 0
+  exit ${exit_code}
 fi
 
 if [[ "${1}" = 'encrypt' ]]; then
